// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) 2025-2026 naskel.com

#![allow(clippy::uninlined_format_args)]
#![allow(clippy::missing_panics_doc)]

//! RTI Interop Temperature Subscriber (v65 - Generated from IDL)
//! Uses Temperature type generated by idl-gen from RTI IDL
//! Subscribes to "Example TemperatureData_Temperature" topic

mod temperature_rti;

use hdds::{Participant, QoS, TransportMode};
use std::thread;
use std::time::Duration;
use temperature_rti::TemperatureData::Temperature;

fn main() {
    println!("+===========================================================+");
    println!("|   HDDS Subscriber - RTI Temperature Interop (v65)       |");
    println!("|   Using type generated from IDL by idl-gen              |");
    println!("+===========================================================+");
    println!();
    println!("Configuration:");
    println!("  - Topic: Example TemperatureData_Temperature (RTI default)");
    println!("  - Type: TemperatureData::Temperature (FQN from IDL)");
    println!("  - Fields: value:f32, timestamp:i32 (matches RTI IDL)");
    println!("  - QoS: RTI defaults (Reliable, Volatile, KeepLast(10))");
    println!("  - Domain: 0");
    println!("  - Transport: UDP Multicast");
    println!();

    // Create participant with UDP transport
    let participant = Participant::builder("rti_temperature_sub_v65")
        .with_transport(TransportMode::UdpMulticast)
        .build()
        .expect("Failed to create participant");

    println!("[OK] Participant created");

    // Create subscriber - type matches RTI IDL exactly!
    // RTI IDL: module TemperatureData { struct Temperature { float value; long timestamp; }; };
    let reader = participant
        .create_reader::<Temperature>(
            "Example TemperatureData_Temperature", // <- RTI topic name
            QoS::rti_defaults(),                   // <- RTI QoS profile
        )
        .expect("Failed to create reader");

    println!("[OK] Temperature reader created");
    println!();
    println!("[*] Waiting for RTI Temperature samples...");
    println!("   (Press Ctrl+C to stop)");
    println!();

    let mut sample_count = 0u64;

    loop {
        thread::sleep(Duration::from_millis(100));

        // Try to read samples
        match reader.take() {
            Ok(Some(sample)) => {
                sample_count += 1;
                println!(
                    "[<] Sample #{}: Temperature = {:.2}  degC (timestamp: {})",
                    sample_count, sample.value, sample.timestamp
                );
            }
            Ok(None) => {
                // No data available yet
            }
            Err(e) => {
                eprintln!("[X] Error reading sample: {:?}", e);
            }
        }
    }
}
