#!/bin/bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright (c) 2025-2026 naskel.com

# Generate all typed sample code from IDL files using hddsgen.
#
# Usage: ./generate.sh <path_to_hdds_gen>
#
#   path_to_hdds_gen  Root of the hdds_gen repository (must already be built).
#                     The script expects target/release/hddsgen inside it.
#
# Examples:
#   ./generate.sh /projects/public/hdds_gen
#   ./generate.sh ../hdds_gen

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <path_to_hdds_gen>"
    echo ""
    echo "  path_to_hdds_gen  Root of the hdds_gen repository (already built)"
    exit 1
fi

HDDS_GEN_ROOT="$(cd "$1" && pwd)"
HDDSGEN="$HDDS_GEN_ROOT/target/release/hddsgen"

if [ ! -x "$HDDSGEN" ]; then
    echo "ERROR: $HDDSGEN not found or not executable"
    echo "Build it first:  cd $1 && cargo build --release"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SAMPLES_DIR="$(dirname "$SCRIPT_DIR")"
IDL_DIR="$SAMPLES_DIR/idl"

echo "hddsgen: $HDDSGEN"
echo "version: $($HDDSGEN --version 2>/dev/null || echo 'unknown')"
echo ""

# lang spec format — "target:subdir:ext"
LANGS_CCP="c:c/generated:.h cpp:cpp/generated:.hpp python:python/generated:.py"
LANGS_RUST="rust:rust/generated:.rs"

count=0

gen() {
    local lang="$1" idl="$2" out="$3"
    $HDDSGEN gen "$lang" "$IDL_DIR/$idl" -o "$out"
    count=$((count + 1))
}

# Lowercase name for Rust output filenames (HelloWorld -> helloworld)
rs_name() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

# ── 01_basics ────────────────────────────────────────────────────────
echo "=== 01_basics ==="
BASICS_IDLS="HelloWorld KeyedData"

for spec in $LANGS_CCP; do
    IFS=: read -r target dir ext <<< "$spec"
    outdir="$SAMPLES_DIR/01_basics/$dir"
    mkdir -p "$outdir"
    for name in $BASICS_IDLS; do
        gen "$target" "$name.idl" "$outdir/$name$ext"
    done
done

# Rust
outdir="$SAMPLES_DIR/01_basics/rust/generated"
mkdir -p "$outdir"
for name in $BASICS_IDLS; do
    gen rust "$name.idl" "$outdir/$(rs_name "$name").rs"
done

# Python __init__.py
cat > "$SAMPLES_DIR/01_basics/python/generated/__init__.py" << 'PYEOF'
# Generated by generate.sh - DO NOT EDIT
from .HelloWorld import HelloWorld
from .KeyedData import KeyedData

__all__ = ['HelloWorld', 'KeyedData']
PYEOF

# 02_qos, 04-07 use symlinks to 01_basics — create them if missing
for cat in 02_qos 04_discovery 05_security 06_performance 07_advanced; do
    for sublang in c cpp; do
        link="$SAMPLES_DIR/$cat/$sublang/generated"
        target="../../01_basics/$sublang/generated"
        if [ -d "$SAMPLES_DIR/$cat/$sublang" ] && [ ! -e "$link" ]; then
            ln -s "$target" "$link"
            echo "  symlink: $cat/$sublang/generated -> $target"
        fi
    done
done

# ── 03_types ─────────────────────────────────────────────────────────
echo ""
echo "=== 03_types ==="
TYPES_IDLS="Arrays Bits Enums Maps Nested Optional Primitives Sequences Strings Unions"

for spec in $LANGS_CCP; do
    IFS=: read -r target dir ext <<< "$spec"
    outdir="$SAMPLES_DIR/03_types/$dir"
    mkdir -p "$outdir"
    for name in $TYPES_IDLS; do
        gen "$target" "$name.idl" "$outdir/$name$ext"
    done
done

# Rust — includes extra IDLs beyond the base 10
TYPES_RUST_IDLS="$TYPES_IDLS Benchmark HelloWorld Interop KeyedData ROS2Types Usecases"
outdir="$SAMPLES_DIR/03_types/rust/generated"
mkdir -p "$outdir"
for name in $TYPES_RUST_IDLS; do
    gen rust "$name.idl" "$outdir/$(rs_name "$name").rs"
done

# Rust mod.rs
{
    echo "// Generated by generate.sh - DO NOT EDIT"
    for name in $TYPES_RUST_IDLS; do
        echo "pub mod $(rs_name "$name");"
    done
} > "$outdir/mod.rs"

# Python __init__.py
cat > "$SAMPLES_DIR/03_types/python/generated/__init__.py" << 'PYEOF'
# Generated by generate.sh - DO NOT EDIT
from .Primitives import Primitives
from .Strings import Strings
from .Sequences import LongSeq, StringSeq, BoundedLongSeq, Sequences
from .Arrays import Arrays
from .Maps import StringLongMap, LongStringMap, Maps
from .Enums import Color, Status, Enums
from .Unions import DataKind, DataValue, Unions
from .Nested import Point, Pose, Robot
from .Bits import Permissions, StatusFlags, Bits
from .Optional import OptionalFields

__all__ = [
    'Primitives',
    'Strings',
    'LongSeq', 'StringSeq', 'BoundedLongSeq', 'Sequences',
    'Arrays',
    'StringLongMap', 'LongStringMap', 'Maps',
    'Color', 'Status', 'Enums',
    'DataKind', 'DataValue', 'Unions',
    'Point', 'Pose', 'Robot',
    'Permissions', 'StatusFlags', 'Bits',
    'OptionalFields',
]
PYEOF

# ── Extended Rust-only categories ────────────────────────────────────
echo ""
echo "=== Rust-only categories ==="

gen_rust_category() {
    local cat="$1"
    shift
    local outdir="$SAMPLES_DIR/$cat/rust/generated"
    mkdir -p "$outdir"
    for name in "$@"; do
        gen rust "$name.idl" "$outdir/$(rs_name "$name").rs"
    done
}

# 05_security
if [ -d "$SAMPLES_DIR/05_security/rust" ]; then
    # SecurityTypes is not a standalone IDL — it's hand-written Rust.
    # Only generate if a matching IDL exists.
    echo "  05_security: skipped (no matching IDL)"
fi

# 08_interop
if [ -d "$SAMPLES_DIR/08_interop/rust" ]; then
    gen_rust_category 08_interop Interop
fi

# 09_ros2
if [ -d "$SAMPLES_DIR/09_ros2/rust" ]; then
    gen_rust_category 09_ros2 ROS2Types
fi

# 10_usecases
if [ -d "$SAMPLES_DIR/10_usecases/rust" ]; then
    gen_rust_category 10_usecases Usecases
fi

echo ""
echo "=== Done: $count files generated ==="
